version: '3.8'

services:
  backend:
    build:
      context: ./app
      dockerfile: Dockerfile
    env_file:
      .env
#      MONGODB_URL: mongodb://mongo:mongo@mongo/?retryWrites=true&w=majority&appName=Cluster0
    ports: ['8000:8000']
    volumes:
      - ./app:/app:delegated,rw
      - backend_data:/home/app/media
    networks:
      - waste_management_net

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    volumes:
      - mongo_db_data:/data/db
    networks:
      - waste_management_net
    expose:
      - "27017"
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    restart: always
    ports: ['8081:8081']
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://mongo:mongo@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    networks:
      - waste_management_net

  redis:
    image: redis:alpine
    container_name: redis-cache
    restart: on-failure
    ports:
      - '6379:6379'
    command: redis-server
    volumes:
      - cache:/data
    networks:
      - waste_management_net

volumes:
  mongo_db_data:
  backend_data:
  cache:

networks:
  waste_management_net:
