version: '3.8'

services:
  backend:
    build:
      context: ./app
      dockerfile: Dockerfile
    environment:
      MONGODB_URL: mongodb://mongo:mongo@mongo/?retryWrites=true&w=majority&appName=Cluster0
    ports: ['8000:8000']

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://mongo:mongo@mongo:27017/
      ME_CONFIG_BASICAUTH: false
